title       = "lemmy"
baseURL     = "https://lemmy-cli.tamnd.com/"
description = "A command line for lemmy."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/lemmy-cli"
